"""create tables

Revision ID: 3faa77554b82
Revises: 
Create Date: 2025-08-18 16:29:20.310235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3faa77554b82'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'pedidos',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('distribuidor', sa.String(), nullable=False, index=True),
        sa.Column('fecha', sa.Date(), nullable=False, index=True),
        sa.Column('valor', sa.Numeric(12, 2), nullable=False),
        sa.Column('descripcion', sa.String(), nullable=True),
    )
    op.create_index(op.f('ix_pedidos_fecha_distribuidor'), 'pedidos', ['fecha', 'distribuidor'], unique=False)

    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resultados_sorteo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('numero_ganador', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ganadores', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('resultados_sorteo_pkey'))
    )
    op.create_index(op.f('ix_resultados_sorteo_id'), 'resultados_sorteo', ['id'], unique=False)
    op.create_table('verificaciones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('archivo_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('creado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('verificaciones_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('verificaciones_pkey'))
    )
    op.create_index(op.f('ix_verificaciones_id'), 'verificaciones', ['id'], unique=False)
    op.create_table('pedidos',
    sa.Column('distribuidor', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('valor', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False)
    )
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('referido_por', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('saldo', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('verificado', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('fecha_registro', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ultima_recompensa', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['referido_por'], ['usuarios.id'], name=op.f('usuarios_referido_por_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('usuarios_pkey'))
    )
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('resultado_sorteo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('numero_ganador', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ganadores', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('resultado_sorteo_pkey'))
    )
    op.create_index(op.f('ix_resultado_sorteo_id'), 'resultado_sorteo', ['id'], unique=False)
    # ### end Alembic commands ###
